In [ ]:
import numpy as np

In [ ]:
cvalue = [32.2,33.8,29.2,34.6,32.7,30.1,33.4,26.1,27.7,35.7]

In [ ]:
type(cvalue)

เปลี่ยนจาก list เป็น array เพื่อง่ายต่อการจัดการ Operation

In [ ]:
c = np.array(cvalue)

In [ ]:
type(c)

In [ ]:
print(c)

In [ ]:
c*9/5+32

In [ ]:
l = [51,10,20,93,19,72,3,61,12,62]

In [ ]:
type(l)

list

In [ ]:
ages = np.array(l)

In [ ]:
2566-ages

Creating array: np.arange()

In [ ]:
x = np.arange(1,10,3)
print(x)

[1 4 7]


Creating array: np.linspace()

In [ ]:
y = np.linspace(1,10,7)
print(y)

[ 1.   2.5  4.   5.5  7.   8.5 10. ]


In [ ]:
%%time
samples = np.random.uniform(0,30, size = 1000000)
samples_list = samples.tolist()

CPU times: user 25.9 ms, sys: 40.1 ms, total: 65.9 ms
Wall time: 64.9 ms


In [ ]:
samples[:10]

array([21.66095118, 23.28179814, 18.35339213,  0.74275639,  7.04007027,
        2.42898728,  4.63268142, 16.20866891,  5.6819017 , 14.28686984])

In [ ]:
np.max(samples)

29.99997829367281

In [ ]:
t = [15,10, 20, 39, 19, 27, 3, 16, 21, 26]

In [ ]:
d = [['a', 15],['b',10],['c', 39]]

In [ ]:
s = np.sort(t)

In [ ]:
ts = s[::-1]
ts

array([39, 27, 26, 21, 20, 19, 16, 15, 10,  3])

In [ ]:
ts[0:3]

array([39, 27, 26])